apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-cm.warm-metal.tech
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-configmap-warm-metal
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-configmap-warm-metal
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
    - update
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-configmap-warm-metal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-configmap-warm-metal
subjects:
  - kind: ServiceAccount
    name: csi-configmap-warm-metal
    namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-configmap-warm-metal
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-configmap-warm-metal
  template:
    metadata:
      labels:
        app: csi-configmap-warm-metal
    spec:
      hostNetwork: true
      serviceAccountName: csi-configmap-warm-metal
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-configmap.warm-metal.tech /registration/csi-configmap.warm-metal.tech-reg.sock"]
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-configmap.warm-metal.tech/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - name: plugin
          image: docker.io/warmmetal/csi-configmap:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-endpoint=$(CSI_ENDPOINT)"
            - "-node=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/lib/warm-metal/cm-volume
              name: cm-source-root
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-configmap.warm-metal.tech
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/warm-metal/cm-volume
            type: DirectoryOrCreate
          name: cm-source-root
